export const AUTH_REQUEST = "AUTH_REQUEST"
export const AUTH_REQUEST_SUCCESS = "AUTH_REQUEST_SUCCESS"
export const AUTH_REQUEST_ERROR = "AUTH_REQUEST_ERROR"
export const REG_REQUEST = "REG_REQUEST"
export const REG_REQUEST_SUCCESS = "REG_REQUEST_SUCCESS"
export const REG_REQUEST_ERROR = "REG_REQUEST_ERROR"
export const RESET_REQUEST = "RESET_REQUEST"
export const RESET_REQUEST_SUCCESS = "RESET_REQUEST_SUCCESS"
export const RESET_REQUEST_ERROR = "RESET_REQUEST_ERROR"
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST"
export const RESET_PASSWORD_REQUEST_SUCCESS = "RESET_PASSWORD_REQUEST_SUCCESS"
export const RESET_PASSWORD_REQUEST_ERROR = "RESET_PASSWORD_REQUEST_ERROR"
export const REFRESH = "REFRESH"
export const ACTIVATE_REQUEST = "ACTIVATE_REQUEST"
export const ACTIVATE_REQUEST_SUCCESS = "ACTIVATE_REQUEST_SUCCESS"
export const ACTIVATE_REQUEST_ERROR = "ACTIVATE_REQUEST_ERROR"
export const LOGOUT = "LOGOUT"
export const SET_IS_AUTH = "SET_IS_AUTH"

export default {
  AUTH_REQUEST,
  AUTH_REQUEST_SUCCESS,
  AUTH_REQUEST_ERROR,
  REG_REQUEST,
  REG_REQUEST_SUCCESS,
  REG_REQUEST_ERROR,
  RESET_REQUEST,
  RESET_REQUEST_SUCCESS,
  RESET_REQUEST_ERROR,
  RESET_PASSWORD_REQUEST,
  RESET_PASSWORD_REQUEST_SUCCESS,
  RESET_PASSWORD_REQUEST_ERROR,
  REFRESH,
  ACTIVATE_REQUEST,
  ACTIVATE_REQUEST_SUCCESS,
  ACTIVATE_REQUEST_ERROR,
  SET_IS_AUTH,
}