export const GET_BLOGGERS_REQUEST = "GET_BLOGGERS_REQUEST"
export const  GET_BLOGGERS_SUCCESS = "GET_BLOGGERS_SUCCESS"
export const GET_BLOGGERS_ERROR = "GET_BLOGGERS_ERROR"
export const GET_BLOGGER_REQUEST = "GET_BLOGGER_REQUEST"
export const  GET_BLOGGER_SUCCESS = "GET_BLOGGER_SUCCESS"
export const GET_BLOGGER_ERROR = "GET_BLOGGER_ERROR"

export default {
  GET_BLOGGERS_REQUEST,
  GET_BLOGGERS_SUCCESS,
  GET_BLOGGERS_ERROR,
  GET_BLOGGER_REQUEST,
  GET_BLOGGER_SUCCESS,
  GET_BLOGGER_ERROR,
}