export const GET_BLOGGER_INSTAGRAM_REQUEST = "GET_BLOGGER_INSTAGRAM_REQUEST"
export const GET_BLOGGER_INSTAGRAM_SUCCESS = "GET_BLOGGER_INSTAGRAM_SUCCESS"
export const GET_BLOGGER_INSTAGRAM_ERROR = "GET_BLOGGER_INSTAGRAM_ERROR"
export const GET_BLOGGER_INSTAGRAM_DELETE = "GET_BLOGGER_INSTAGRAM_DELETE"

export default {
  GET_BLOGGER_INSTAGRAM_REQUEST,
  GET_BLOGGER_INSTAGRAM_SUCCESS,
  GET_BLOGGER_INSTAGRAM_ERROR,
  GET_BLOGGER_INSTAGRAM_DELETE,
}