export const GET_COMPANIES_REQUEST = "GET_COMPANIES_REQUEST"
export const GET_COMPANIES_SUCCESS = "GET_COMPANIES_SUCCESS"
export const GET_COMPANIES_ERROR = "GET_COMPANIES_ERROR"
export const GET_MY_COMPANIES_REQUEST = "GET_MY_COMPANIES_REQUEST"
export const GET_MY_COMPANIES_SUCCESS = "GET_MY_COMPANIES_SUCCESS"
export const GET_MY_COMPANIES_ERROR = "GET_MY_COMPANIES_ERROR"
export const ADD_COMPANY_REQUEST = "ADD_COMPANY_REQUEST"
export const ADD_COMPANY_SUCCESS = "ADD_COMPANY_SUCCESS"
export const ADD_COMPANY_ERROR = "ADD_COMPANY_ERROR"
export const GET_COMPANY_REQUEST = "GET_COMPANY_REQUEST"
export const GET_COMPANY_SUCCESS = "GET_COMPANY_SUCCESS"
export const GET_COMPANY_ERROR = "GET_COMPANY_ERROR"
export const CLEAR_COMPANY = "CLEAR_COMPANY"
export const UPDATE_COMPANY_REQUEST = "UPDATE_COMPANY_REQUEST"
export const UPDATE_COMPANY_SUCCESS = "UPDATE_COMPANY_SUCCESS"
export const UPDATE_COMPANY_ERROR = "UPDATE_COMPANY_ERROR"
export const DELETE_COMPANY_REQUEST = "UPDATE_COMPANY_REQUEST"
export const DELETE_COMPANY_SUCCESS = "UPDATE_COMPANY_SUCCESS"
export const DELETE_COMPANY_ERROR = "UPDATE_COMPANY_ERROR"
export const GET_PROFILE_CATEGORIES_REQUEST = "GET_PROFILE_CATEGORIES_REQUEST"
export const GET_PROFILE_CATEGORIES_SUCCESS = "GET_PROFILE_CATEGORIES_SUCCESS"
export const GET_PROFILE_CATEGORIES_ERROR = "GET_PROFILE_CATEGORIES_ERROR"
export const GET_LINKED_BLOGGERS_REQUEST = "GET_LINKED_BLOGGERS_REQUEST"
export const GET_LINKED_BLOGGERS_SUCCESS = "GET_LINKED_BLOGGERS_SUCCESS"
export const GET_LINKED_BLOGGERS_ERROR = "GET_LINKED_BLOGGERS_ERROR"

export default {
  GET_COMPANIES_REQUEST,
  GET_COMPANIES_SUCCESS,
  GET_COMPANIES_ERROR,
  GET_MY_COMPANIES_REQUEST,
  GET_MY_COMPANIES_SUCCESS,
  GET_MY_COMPANIES_ERROR,
  ADD_COMPANY_REQUEST,
  ADD_COMPANY_SUCCESS,
  ADD_COMPANY_ERROR,
  GET_COMPANY_REQUEST,
  GET_COMPANY_SUCCESS,
  GET_COMPANY_ERROR,
  UPDATE_COMPANY_REQUEST,
  UPDATE_COMPANY_SUCCESS,
  UPDATE_COMPANY_ERROR,
  DELETE_COMPANY_REQUEST,
  DELETE_COMPANY_SUCCESS,
  DELETE_COMPANY_ERROR,
  GET_PROFILE_CATEGORIES_REQUEST,
  GET_PROFILE_CATEGORIES_SUCCESS,
  GET_PROFILE_CATEGORIES_ERROR,
  GET_LINKED_BLOGGERS_REQUEST,
  GET_LINKED_BLOGGERS_SUCCESS,
  GET_LINKED_BLOGGERS_ERROR,
  CLEAR_COMPANY,
}